services:
  mysql:
    image: mysql:8.4
    container_name: user-mysql
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uuser", "-puserpass"]
      interval: 10s
      timeout: 5s
      retries: 10

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: user-redpanda
    command: [
      "redpanda", "start",
      "--overprovisioned",
      "--smp", "1",
      "--memory", "512M",
      "--reserve-memory", "0M",
      "--check=false",
      "--kafka-addr", "PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092",
      "--advertise-kafka-addr", "PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092"
    ]
    ports:
      - "9092:9092"
      - "9644:9644"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9644/v1/status/ready"]
      interval: 10s
      timeout: 5s
      retries: 10

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    depends_on:
      mysql:
        condition: service_healthy
      redpanda:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8080
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: userdb
      DB_USERNAME: user
      DB_PASSWORD: userpass
      KAFKA_BOOTSTRAP_SERVERS: redpanda:29092
      # Provide a long random secret for signing JWTs. Override via environment in production.
      JWT_SECRET: "change-this-to-a-long-random-secret"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  mysql_data:
